// react-http/src/App.js
import React, {useEffect, useState} from 'react';
import {getProductsList} from "./Products.service";


function App() {

    const [products, setProducts] = useState([]);

    useEffect(() => {
        getProductsList()
            .then(items => setProducts(items))
            .catch(error => console.log('error occurred ', error));
    }, []);

    return (
        <>
        {products.map(product => (
            <div key={product.id}>
                <b>{product.name}</b>
                <br /> {product.price} - VAT: {product.vat}
                <br /> {product.createdAt.format('DD-MM-YYYY HH:mm')}
            </div>
        ))}
        </>
    );
}

export default App;

// angular-http/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductModel, ProductsService } from './products.service';
import { take } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  public products: ProductModel[];

  constructor(private productsService: ProductsService) {
  }

  public ngOnInit(): void {
    this.productsService.getProductsList()
      .pipe(
        take(1)
      ).subscribe(
      products => this.products = products,
      error => console.log('error occurred ', error)
    );
  }
}

<ng-container *ngFor="let product of products">
  <div>
    <b>{{product.name}}</b>
    <br /> {{product.price}} - VAT: {{product.vat}}
    <br /> {{product.createdAt.format('DD-MM-YYYY HH:mm')}}
  </div>
</ng-container>
